[tools]
"cargo:eza" = "latest"
"cargo:treefmt" = "latest"
"jujutsu" = "latest"

[tasks.lint]
description = "Format the project tree"
alias = "f"
run = [
  "mise fmt",
  "treefmt --clear-cache --fail-on-change --allow-missing-formatter",
]

[tasks.push]
description = "Push the changes to the main branch"
alias = "up"
run = [
  #   "jj --version",
  "jj describe",
  "jj bookmark set main --revision=@",
  "jj git push",
]

[tasks.files]
description = "List the files in the current directory"
alias = "fl"
run = "eza --icons --long --group-directories-first --git"

[tasks.tree]
description = "List the files recursively from the current directory"
alias = "ft"
run = "eza --icons --long --group-directories-first --git --tree"

[tasks.test]
run = 'echo myarg={{cwd}}'
# run = 'echo myarg={{arg(name="path")}}'

# execute: mise run usage-env-example
# outputs: myarg=foo

# execute: mise run usage-env-example bar
# outputs: myarg=bar
