SELECT
    TOP(1000)[sls_ord_num]
    , [sls_prd_key]
    , [sls_cust_id]
    , [sls_order_dt]
    , [sls_ship_dt]
    , [sls_due_dt]
    , [sls_sales]
    , [sls_quantity]
    , [sls_price]
FROM [BaraaWarehouse].[bronze].[crm_sales_details]
