# services:
#   sqlserver:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     container_name: mssql
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD="P@ssw0rd"
#       - MSSQL_PID=Express
#     ports:
#       - "14330:1433"
#     volumes:
#       - mssql_data:/var/opt/mssql
#       - ../data:/data
#     restart: unless-stopped

# volumes:
#   mssql_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "14330:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ../data:/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mssql_data:
