#let project = (
  metadata: (
    name: "datum",
    title: "Datum",
    subtitle: "From Data Enthusiast to Guru, One Datum at a Time",
    author: "Craig 'Craole' Cole",
    tagline: "Every data journey begins with a single datum.",
    version: "1.0.0",
    date: datetime.today(),
    keywords: ("data", "analysis", "documentation"),
    language: "en",
  ),
  layout: (
    paper: "us-letter",
    margin: (x: 1.8cm, top: 2.8cm, bottom: 2cm),
    show-title-page: true,
    show-toc: true,
    show-page-numbers: true,
    show-footer: true,
    show-header: false,
    line-height: 1.5,
    paragraph-spacing: 1.2em,
    paragraph-indent: 0em,
    paragraph-justify: true,
    list-indent: 1.5em,
    list-spacing: 0.6em,
    enum-indent: 1.5em,
    enum-spacing: 0.6em,
    enum-numbering: "1.a.i.",
    heading-numbering: "1.1",
    border-radius: 8pt,
    gradient-angle: 45deg,
    gradient-angle-secondary: 90deg,
    spacing: (
      xs: 0.4em,
      sm: 0.8em,
      md: 1.2em,
      lg: 1.8em,
      xl: 2.4em,
      xxl: 3.2em,
    ),
    shadow: (
      enabled: true,
      color: rgb("#00000015"),
      offset: (x: 0pt, y: 2pt),
      blur: 4pt,
    ),
    title-page: (
      margin: (x: 2cm, y: 3cm),
      logo-spacing: 2em,
      title-subtitle-spacing: 0.8em,
      decorative-spacing: 1.5em,
      footer-spacing: 1cm,
      grid-gutter: 2em,
    ),
    toc: (
      header-inset: 1.5em,
      header-spacing: 1.5em,
      entry-spacing: (
        level1: 0.8em,
        level2: 0.4em,
        level3: 0.2em,
      ),
      depth: 3,
      indent: 0em,
      entry-indent: (
        level1: 0em,
        level2: 1em,
        level3: 2em,
      ),
    ),
    callout: (
      inset: 1.5em,
      icon-spacing: 0.8em,
      title-spacing: 0.8em,
      border-width: (left: 4pt, rest: 1pt),
      bg-lighten-amount: 3%,
    ),
    code: (
      inset: 1.5em,
      header-inset: (x: 1.5em, y: 0.8em),
      content-inset: 1.5em,
      border-width: 1pt,
    ),
    table: (
      border-width: 1pt,
      cell-padding: (x: 1em, y: 0.6em),
      header-padding: (x: 1em, y: 0.8em),
      zebra-enabled: true,
    ),
    heading: (
      spacing: (
        before: (h1: "lg", h2: "lg", h3: "md", h4: "md"),
        after: (h1: "md", h2: "md", h3: "sm", h4: "sm"),
      ),
      inset: 1.5em,
      underline-width: 2pt,
      underline-spacing: 0.5em,
    ),
    footer: (
      column-count: 3,
      column-gutter: 2em,
      alignment: (left: left, center: center, right: right),
    ),
    page-numbering: (
      format: "1",
      start: 1,
    ),
    link: (
      decoration: none,
      weight: "medium",
    ),
    emphasis: (
      style: "italic",
    ),
    strong: (
      weight: "bold",
    ),
    list-markers: ([•], [◦], [▪]),
    text-hyphenate: true,
    decorative-line: (
      widths: (40%, 60%, 30%),
      strokes: (3pt, 1pt, 2pt),
      spacing: 0.5em,
    ),
  ),
  font: (
    family: (
      serif: ("New Computer Modern", "Times New Roman"),
      sans: ("Dank Mono", "Arial"),
      mono: ("Maple Mono NF", "Monaspace Radon Var", "Consolas"),
      display: ("Monaspace Radon Var", "Arial"),
    ),
    size: (
      base: 11pt,
      title: 2.6em,
      subtitle: 1.4em,
      h1: 2.0em,
      h2: 1.6em,
      h3: 1.3em,
      h4: 1.1em,
      h5: 1.0em,
      small: 0.9em,
      footnote: 0.8em,
      caption: 0.85em,
      copyright: 0.7em,
      icon: 1.2em,
      code-header: 0.9em,
    ),
    weight: (
      thin: "thin",
      light: "light",
      normal: "regular",
      medium: "medium",
      semibold: "semibold",
      bold: "bold",
      extrabold: "extrabold",
      black: "black",
    ),
  ),
  themes: (
    light: (
      primary: rgb("#2563eb"),
      secondary: rgb("#7c3aed"),
      accent: rgb("#059669"),
      text: rgb("#1f2937"),
      text-light: rgb("#6b7280"),
      text-muted: rgb("#9ca3af"),
      bg: rgb("#ffffff"),
      bg-alt: rgb("#f9fafb"),
      bg-code: rgb("#f3f4f6"),
      border: rgb("#e5e7eb"),
      border-light: rgb("#f3f4f6"),
      success: rgb("#059669"),
      warning: rgb("#d97706"),
      error: rgb("#dc2626"),
      info: rgb("#2563eb"),
    ),
    dark: (
      primary: rgb("#60a5fa"),
      secondary: rgb("#a78bfa"),
      accent: rgb("#34d399"),