#let font = (
  family: (
    serif: ("New Computer Modern", "Times New Roman"),
    sans: ("Dank Mono", "Arial"),
    mono: ("Maple Mono NF", "Monaspace Radon Var", "Consolas"),
    display: ("Monaspace Radon Var", "Arial"),
  ),
  size: (
    base: 11pt,
    title: 2.6em,
    subtitle: 1.4em,
    h1: 2.0em,
    h2: 1.6em,
    h3: 1.3em,
    h4: 1.1em,
    h5: 1.0em,
    small: 0.9em,
    footnote: 0.8em,
    caption: 0.85em,
    copyright: 0.7em,
    icon: 1.2em,
    code-header: 0.9em,
  ),
  weight: (
    thin: "thin",
    light: "light",
    normal: "regular",
    medium: "medium",
    semibold: "semibold",
    bold: "bold",
    extrabold: "extrabold",
    black: "black",
  ),
)
