#let icon = (
  annotations: (
    home: "🏠",
    search: "🔍",
    settings: "⚙️",
    user: "👤",
    mail: "📧",
    calendar: "📅",
    file: "📄",
    idea: "💡",
    note: "📝",
    tip: "💡",
    warning: "⚠️",
    error: "❌",
    success: "✅",
    info: "ℹ️",
    question: "❓",
    star: "⭐",
    heart: "❤️",
  ),
  document: (
    roadmap: "🗺️",
    toolchain: "🔧",
    project: "📁",
    learning: "📚",
    architecture: "🏗️",
    api: "🔌",
    guide: "📖",
    reference: "📋",
    tutorial: "🎓",
  ),
  status: (
    todo: "⏳",
    doing: "🔄",
    done: "✅",
    blocked: "🚫",
    review: "👀",
    experimental: "🧪",
    stable: "✅",
    deprecated: "⚠️",
    archive: "📦",
  ),
  priority: (
    critical: "🔥",
    high: "🔴",
    medium: "🟡",
    low: "🟢",
    zero: "⚪",
  ),
  tech: (
    python: "🐍",
    rust: "🦀",
    database: "🗄️",
    cloud: "☁️",
    docker: "🐳",
    git: "📦",
    spark: "⚡",
    airflow: "🌊",
    kafka: "📡",
    kubernetes: "☸️",
    typescript: "📘",
    javascript: "📙",
    react: "⚛️",
    vue: "💚",
    angular: "🅰️",
  ),
)
