services:
  sqlserver:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@SSw0rd!
      - MYSQL_DATABASE=default
    ports:
      - "3306:3306"
    # networks:
    #   - mysql_network
    volumes:
      - ../databases/mysql:/var/opt/mysql
      - ../../data:/data
    restart: unless-stopped

  # networks:
  # mysql_network:
  #   driver: bridge
