[package]
name = "extractor"
description = "Extract files from archives"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
keywords = ["extractor", "file", "filesystem", "tool"]

[lints]
workspace = true

[dependencies]
